### ISSUE TITLE
(Idea) Hover over the icon to display the list, instead of having the list visible at all times.

### ISSUE THREAD

**Issue by Rynhardt-GitHub** [Noshei/GatheringTracker#19]
Hello,

Would it be possible to add an option for a box that shows the total gold and when you hover over it, a list of all the collected items appears?

I prefer keeping my UI clean, but I enjoy seeing the items I've gathered while collecting. Having the list on screen at all times can be overwhelming since it can get quite long and cover a significant portion of the screen.

Additionally, a timer would be a great feature, starting with the collection of the first herb, ore, leather, or other materials.

Thanks!

**Comment by Noshei** [comment]
These are 2 interesting ideas.

For hiding the UI part, I will leave that as a possibility for now.  Right now I am working toward adding broker support which could also provide this functionality.  I'm not sure how I would go about adding this, as mouse interaction can get messy since I don't want the display to interfere with mouse clicks

As for the timer, I can probably add that, though I will have to think about how I want to go about it.

**Comment by Noshei** [comment]
I've added the collapse / hover option in v2.5.1.

I still need to add the timer.

**Comment by Noshei** [comment]
I've decided not to add a timer at this time.

**Comment by Rynhardt-GitHub** [comment]
No problem, thanks for the updates!

**Comment by Noshei** [comment]
I went back and looked at adding a timer again and have worked out a way to add it that I'm happy with.  v3.0.4 now includes a Session Timer in the Other filters.  This can be used even if you don't have the Session options enabled, and is reset with the reset session options (keybind, button in settings, or shift right click on the filter/minimap/broker icons)
