### ISSUE TITLE
Window extending all the way to the right bug

### ISSUE THREAD

**Issue by pollexdd** [Noshei/GatheringTracker#7]
Hi this is my first bug report so idk what you need to fix this so sorry if I give bad info. Every time I switch my spec to resto druid gather trackers window bugs and extends all the way to the right. I enabled the debugger but I don't think anything show in the chat. the addon fixes itself when I /reload. I filmed it and all my addons I will link down below.

https://youtu.be/gatEzBM4OGA

hope this is enough love the addon <3.

forgot to add I have the latest version of the addon when I write this :)

**Comment by Noshei** [comment]
this is a known bug because of how elvUI works.  I've tried to fix this a number of times, but haven't been able to get a good work around.  To address this on your own, if you go into the ElvUI settings and look for the settings for other addons, and uncheck the option for Ace3, that should resolve this.

**Comment by pollexdd** [comment]
ok thx it fixed it keep up the good work <3
